profile: my-production-profile # Set to your production AWS profile
region: us-east-1 # Set to your region
suffix: ""
bucket: my-production-bucket
inPrefix: auto
outPrefix: out
bucketTags:
  -
    Key: "project"
    Value: "transcode"
  -
    Key: "role"
    Value: "in-out"
  -
    Key: "service"
    Value: "storage"
  -
    Key: "billing_entity"
    Value: "content"
  -
    Key: "Name"
    Value: ${self:custom.stage.bucket}
lambda:
  memorySize: 128
  timeout: 10
  logRetention: "30"
